# version: '3.8'
services:
  test-db:
    image: postgres:17
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: restaurant_admin
      POSTGRES_PASSWORD: project123
      POSTGRES_DB: restaurant
    networks:
      - briltest

networks:
  briltest:
